<a href="https://colab.research.google.com/github/deepakatAviSoft/february_assignments/blob/main/14_02_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Problem 1**
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
<pre>
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
Output: [ True False False True False]
</pre>


In [3]:
def test_elements_in_second_array(arr1, arr2):
    return np.isin(arr1, arr2)

# Example arrays
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 20])

result = test_elements_in_second_array(array1, array2)
print("Elements of array1 also present in array2:", result)

Elements of array1 also present in array2: [ True False  True False False]


**Problem 2**
Write a NumPy program to get the unique elements of an array
<pre>
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]
</pre>

In [6]:
def get_unique_elements(arr):
    return np.unique(arr)

# Example arrays
array1 = np.array([10, 10, 20, 20, 30, 30])
array2 = np.array([[1, 1], [2, 3]])

print("Original array:")
print(array1)
print("Unique elements of the above array:")
print(get_unique_elements(array1))

print("Original array:")
print(array2)
print("Unique elements of the above array:")
print(get_unique_elements(array2))


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
#####
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


**Problem 3**
Write a NumPy program to sort an along the first, last axis of an array.
<pre>
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]
</pre>

In [7]:
def sort_along_first_and_last_axis(arr):
    sorted_first_axis = np.sort(arr, axis=0)
    sorted_last_axis = np.sort(arr, axis=1)
    return sorted_first_axis, sorted_last_axis

# Sample array
array = np.array([[4, 6], [2, 1]])

print("Original array:")
print(array)

sorted_first_axis, sorted_last_axis = sort_along_first_and_last_axis(array)

print("Sort along the first axis:")
print(sorted_first_axis)

print("Sort along the last axis:")
print(sorted_last_axis)


Original array:
[[4 6]
 [2 1]]
Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis:
[[4 6]
 [1 2]]


**Problem 4**
Write a NumPy program to count the occurrence of a specified item in a given
<pre>
Original array: [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
Sample Output: [4,1,7,3]
Expalnation: 0 has occured 4 times, 10 has occured 1 time, 20 has occured 7 time and so on
</pre>

In [18]:
array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
unique_values, occurrence_count = np.unique(array, return_counts=True)
print(occurrence_count)

[4 1 7 3]


**Problem 5**
Write a NumPy program to remove nan values from a given array.
<pre>
Sample Output:
Original array:
[200. 300. nan nan nan 700.]
After removing nan values:
[200. 300. 700.]
</pre>

In [19]:
array = np.array([200, 300, np.nan, np.nan, 700])
# Remove np.nan values
array_without_nan = array[~np.isnan(array)]

print("Array without np.nan values:")
print(array_without_nan)

Array without np.nan values:
[200. 300. 700.]


**Problem 6**
Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
<pre>
Sample Output:
50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6
</pre>

In [20]:
# Sample array
array = np.array([1, 2, 3, 4, 5])

# Calculate percentiles
percentile_50 = np.percentile(array, 50)
percentile_40 = np.percentile(array, 40)
percentile_90 = np.percentile(array, 90)

# Print percentiles
print("50th percentile (median):")
print(percentile_50)
print("40th percentile:")
print(percentile_40)
print("90th percentile:")
print(percentile_90)


50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6


**Problem 7**
Write a NumPy program to find indices of elements equal to zero in a NumPy array.
<pre>
Sample Output: [1 0 2 0 3 0 4 5 6 7 8]
Original array:
Indices of elements equal to zero of the said array:
[1 3 5]
</pre>

In [21]:
# Sample array
array = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])

# Find indices of elements equal to zero
zero_indices = np.where(array == 0)

# Print original array and zero indices
print("Original array:")
print(array)
print("Indices of elements equal to zero of the said array:")
print(zero_indices[0])


Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]


**Problem 8**
Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
<pre>
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]
</pre>

In [24]:
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])

# Displaying the original array
print("Original array:")
print(x)

# Rounding elements of the array to the nearest integer
x = np.rint(x)
x = np.absolute(x)
print("Round elements of the array to the nearest integer:")
print(x)


Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]


**Problem 9**
Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
<pre>
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]
</pre>

In [27]:
x = np.array([1, 3, 5, 7, 0])

# Displaying the original array
print("Original array: ")
print(x)
x = np.append(x,200) #(array you want to apppend into, append the number)
# Calculating the difference between neighboring elements, element-wise
print("Difference between neighboring elements, element-wise of the said array.")
print(np.diff(x))


Original array: 
[1 3 5 7 0]
Difference between neighboring elements, element-wise of the said array.
[  2   2   2  -7 200]


**Problem 10**
Write a NumPy program to get the indices of the sorted elements of a given array.
<pre>
Expected Output:
Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]
</pre>

In [28]:
# Creating a NumPy array for student IDs
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Displaying the original array
print("Original array:")
print(student_id)

# Sorting the indices of the array's elements in ascending order
i = np.argsort(student_id)

# Displaying the indices of the sorted elements
print("Indices of the sorted elements of a given array:")
print(i)


Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


**Problem 11**
Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
<pre>
Sample output:
Original array:
[ 70 50 20 30 -11 60 50 40]
After partitioning on 4 the position:
[-11 30 20 40 50 50 60 70]
</pre>

In [ ]:
# Creating an array of integers
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])

# Displaying the original array
print("Original array:")
print(nums)

# Partitioning the array at the 4th position
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))


**Problem 12**
Compute the euclidean distance between two arrays a and b.
<pre>
Input:
[1,2,3,4,5]
[4,5,6,7,8]
Euclidean distance is: 6.7082
</pre>

In [30]:
# Input arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# Compute Euclidean distance
euclidean_distance = np.linalg.norm(a - b)

# Print the result
print("Euclidean distance is:", euclidean_distance)


Euclidean distance is: 6.708203932499369


**Problem 13**
Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
<pre>
Input:
array([1, 3, 7, 1, 2, 6, 0, 1])
Desired Output:
array( [2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.
</pre>

In [31]:
def find_peaks(array):
    peaks = []
    for i in range(1, len(array) - 1):
        if array[i] > array[i - 1] and array[i] > array[i + 1]:
            peaks.append(i)
    return np.array(peaks)

# Input array
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Find peaks
peak_positions = find_peaks(a)

# Print result
print("Peak positions:", peak_positions)


Peak positions: [2 5]


**Problem 14**
Find the index of nth repetition of number i .
<pre>
Inputs
array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 (from user)
i = 1 (from user)
Output
8
</pre>

In [32]:
def find_nth_repetition_index(array, n, i):
    indices = np.where(array == i)[0]  # Find indices where i appears
    if len(indices) < n:  # If number of occurrences is less than n
        return -1  # Return -1 indicating not found
    return indices[n - 1]  # Return the index of the nth occurrence

# Input array
arr = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
# i is one and and fith time one repeats on index 8
n = 5
i = 1

# Find nth repetition index
index = find_nth_repetition_index(arr, n, i)

# Print result
print("Index of nth repetition of number", i, "is:", index)


Index of nth repetition of number 1 is: 8
